// 健身术语翻译词汇表
// 用于快速翻译动作名称，无需调用API

const Map<String, String> _termTranslations = {
  // 器械
  'barbell': '杠铃',
  'dumbbell': '哑铃',
  'dumbbells': '哑铃',
  'cable': '绳索',
  'machine': '器械',
  'kettlebell': '壶铃',
  'kettlebells': '壶铃',
  'band': '弹力带',
  'bands': '弹力带',
  'medicine ball': '药球',
  'exercise ball': '健身球',
  'foam roll': '泡沫轴',
  'smith machine': '史密斯机',
  'ez-bar': '曲杆',
  'ez bar': '曲杆',
  
  // 动作类型
  'bench press': '卧推',
  'squat': '深蹲',
  'deadlift': '硬拉',
  'row': '划船',
  'curl': '弯举',
  'press': '推举',
  'raise': '举',
  'flyes': '飞鸟',
  'fly': '飞鸟',
  'pull-up': '引体向上',
  'pullup': '引体向上',
  'pull up': '引体向上',
  'push-up': '俯卧撑',
  'pushup': '俯卧撑',
  'push up': '俯卧撑',
  'lunge': '弓步',
  'dip': '臂屈伸',
  'dips': '臂屈伸',
  'crunch': '卷腹',
  'sit-up': '仰卧起坐',
  'situp': '仰卧起坐',
  'sit up': '仰卧起坐',
  'plank': '平板支撑',
  'extension': '伸展',
  'rollover': '翻滚',
  'rollout': '滚轮',
  'twist': '转体',
  'kickback': '后踢',
  'shrug': '耸肩',
  'pullover': '仰卧臂屈伸',
  'pulldown': '下拉',
  'pull-down': '下拉',
  'pull down': '下拉',
  'pushdown': '下压',
  'push-down': '下压',
  'push down': '下压',
  'clean': '翻举',
  'snatch': '抓举',
  'jerk': '挺举',
  'thrust': '推举',
  'bridge': '桥式',
  'hip thrust': '臀推',
  'hip raise': '臀桥',
  'good morning': '早安式',
  'hack squat': '哈克深蹲',
  'leg press': '腿举',
  'leg curl': '腿弯举',
  'leg extension': '腿屈伸',
  'calf raise': '提踵',
  'calf raises': '提踵',
  
  // 身体部位
  'chest': '胸',
  'back': '背',
  'shoulder': '肩',
  'shoulders': '肩部',
  'leg': '腿',
  'legs': '腿部',
  'arm': '臂',
  'arms': '手臂',
  'bicep': '二头肌',
  'biceps': '二头肌',
  'tricep': '三头肌',
  'triceps': '三头肌',
  'abs': '腹肌',
  'abdominals': '腹肌',
  'ab': '腹',
  'core': '核心',
  'glute': '臀',
  'glutes': '臀部',
  'quad': '四头肌',
  'quads': '股四头肌',
  'quadriceps': '股四头肌',
  'hamstring': '腘绳肌',
  'hamstrings': '腘绳肌',
  'calf': '小腿',
  'calves': '小腿',
  'forearm': '前臂',
  'forearms': '前臂',
  'lat': '背阔肌',
  'lats': '背阔肌',
  'trap': '斜方肌',
  'traps': '斜方肌',
  'delt': '三角肌',
  'delts': '三角肌',
  'deltoid': '三角肌',
  'deltoids': '三角肌',
  'rear delt': '后三角肌',
  'front delt': '前三角肌',
  'side delt': '侧三角肌',
  'oblique': '腹斜肌',
  'obliques': '腹斜肌',
  'lower back': '下背部',
  'middle back': '中背部',
  'upper back': '上背部',
  'adductor': '内收肌',
  'abductor': '外展肌',
  'hip': '髋',
  'neck': '颈',
  'ankle': '踝',
  'wrist': '腕',
  'elbow': '肘',
  'knee': '膝',
  'groin': '腹股沟',
  
  // 方向/位置
  'incline': '上斜',
  'decline': '下斜',
  'flat': '平躺',
  'seated': '坐姿',
  'standing': '站姿',
  'lying': '仰卧',
  'prone': '俯卧',
  'supine': '仰卧',
  'one-arm': '单臂',
  'one arm': '单臂',
  'two-arm': '双臂',
  'two arm': '双臂',
  'single-arm': '单臂',
  'single arm': '单臂',
  'single-leg': '单腿',
  'single leg': '单腿',
  'alternate': '交替',
  'alternating': '交替',
  'close-grip': '窄握',
  'close grip': '窄握',
  'wide-grip': '宽握',
  'wide grip': '宽握',
  'medium grip': '中握',
  'neutral grip': '对握',
  'reverse grip': '反握',
  'overhand': '正握',
  'underhand': '反握',
  'hammer': '锤式',
  'front': '前',
  'rear': '后',
  'side': '侧',
  'lateral': '侧向',
  'overhead': '过顶',
  'behind the neck': '颈后',
  'behind back': '背后',
  
  // 难度/类型
  'beginner': '初级',
  'intermediate': '中级',
  'advanced': '高级',
  'expert': '专家级',
  'compound': '复合',
  'isolation': '孤立',
  'bodyweight': '自重',
  'body only': '自重',
  'body weight': '自重',
  
  // 其他常见词
  'preacher': '牧师凳',
  'concentration': '集中',
  'scaption': '肩胛平面举',
  'upright': '直立',
  'renegade': '叛徒式',
  'sumo': '相扑',
  'bulgarian': '保加利亚',
  'romanian': '罗马尼亚',
  'russian': '俄罗斯',
  'turkish': '土耳其',
  'arnold': '阿诺德',
  'skull crusher': '碎颅者',
  'skullcrusher': '碎颅者',
  'face pull': '面拉',
  'landmine': '地雷管',
  'prowler': '推雪橇',
  'sled': '雪橇',
  'farmer': '农夫',
  'rack': '架',
  'box': '箱',
  'floor': '地板',
  'bench': '凳',
  'step': '台阶',
  'step-up': '登阶',
  'step up': '登阶',
  'jump': '跳',
  'sprint': '冲刺',
  'walk': '走',
  'drag': '拖拽',
  'bound': '跳跃',
  'hop': '单脚跳',
  'skip': '跳绳',
  'climb': '爬',
  'crawl': '爬行',
  'roll': '滚',
  'stretch': '拉伸',
  'smr': '筋膜放松',
  'windmill': '风车',
  'around the world': '环绕世界',
  'around the worlds': '环绕世界',
  'pallof': '帕洛夫',
  'dead bug': '死虫',
  'bird dog': '鸟狗',
  'superman': '超人',
  'hollow': '空心',
  'hollow body': '空心支撑',
  'bear': '熊',
  'spider': '蜘蛛',
  'gator': '鳄鱼',
  'inchworm': '毛毛虫',
  'frog': '青蛙',
  'pike': '屈体',
  'tuck': '收膝',
  'jackknife': '折刀',
  'scissor': '剪刀',
  'flutter': '扑打',
  'bicycle': '自行车',
  'mountain climber': '登山者',
  'mountain climbers': '登山者',
  'burpee': '波比跳',
  'battle rope': '战绳',
  'battling ropes': '战绳',
  'rope climb': '爬绳',
  'rope jumping': '跳绳',
  'rope skipping': '跳绳',
  'vertical': '垂直',
  'horizontal': '水平',
  'static': '静态',
  'dynamic': '动态',
  'isometric': '等长',
  'plyo': '增强式',
  'plyometric': '增强式',
  'power': '爆发力',
  'explosive': '爆发',
  'strength': '力量',
  'cardio': '有氧',
  'aerobic': '有氧',
  'anaerobic': '无氧',
  'endurance': '耐力',
  'mobility': '灵活性',
  'stability': '稳定性',
  'balance': '平衡',
  'control': '控制',
  'assisted': '辅助',
  'weighted': '负重',
  'loaded': '负重',
  'unilateral': '单侧',
  'bilateral': '双侧',
};

/// 翻译动作名称
String translateExerciseName(String englishName) {
  String result = englishName;
  
  // 按长度排序，优先匹配更长的词组
  final sortedTerms = _termTranslations.keys.toList()
    ..sort((a, b) => b.length.compareTo(a.length));
  
  for (final term in sortedTerms) {
    if (result.toLowerCase().contains(term)) {
      // 保留大小写敏感的替换
      result = result.replaceAll(RegExp(term, caseSensitive: false), _termTranslations[term]!);
    }
  }
  
  // 清理多余空格和连字符
  result = result.replaceAll(RegExp(r'\s+'), ' ').trim();
  result = result.replaceAll(RegExp(r'-+'), '-');
  result = result.replaceAll(RegExp(r'\s*-\s*'), '-');
  
  // 如果结果还是以英文为主，尝试更激进的替换
  if (RegExp(r'[a-zA-Z]').hasMatch(result)) {
    // 替换剩余的常见词
    result = result.replaceAll(RegExp('with', caseSensitive: false), '带');
    result = result.replaceAll(RegExp('from', caseSensitive: false), '从');
    result = result.replaceAll(RegExp('to', caseSensitive: false), '到');
    result = result.replaceAll(RegExp('on', caseSensitive: false), '上');
    result = result.replaceAll(RegExp('off', caseSensitive: false), '下');
    result = result.replaceAll(RegExp('and', caseSensitive: false), '与');
    result = result.replaceAll(RegExp('or', caseSensitive: false), '或');
    result = result.replaceAll(RegExp('the', caseSensitive: false), '');
    result = result.replaceAll(RegExp('a ', caseSensitive: false), '');
    result = result.replaceAll(RegExp('an ', caseSensitive: false), '');
  }
  
  return result.trim();
}
